services:
  reversi_web-api:
    build:
      context: ./web-api
    container_name: reversi_web-api
    volumes:
      - ./web-api:/project/web-api
      - /project/web-api/.gradle
    ports:
      - "18080:8080"
      - "15005:5005"
    env_file:
      - ./web-api/app-settings.env

  reversi_web-front:
    build:
      context: ./web-front
    container_name: reversi_web-front
    volumes:
      - ./web-front:/projects
    depends_on:
      - reversi_web-api
    ports:
      - "14200:4200"

  reversi_e2e-test:
    build:
      context: ./e2e-test
    container_name: reversi_e2e-test
    depends_on:
      - reversi_web-api
      - reversi_web-front
