version: '3'

services:
  demo_db:
    container_name: demo_db
    build:
      context: ./db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  demo_web-api:
    build:
      context: ./web-api
    container_name: demo_web-api
    volumes:
      - ./web-api:/project/web-api
      - /project/web-api/.gradle
    depends_on:
      - demo_db
    ports:
      - "18080:8080"
      - "15005:5005"
    env_file:
      - ./web-api/app-settings.env
