services:
  reversi_web-api:
    build:
      context: ./web-api
    container_name: reversi_web-api
    volumes:
      - ./web-api:/project/web-api
      - /project/web-api/.gradle
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - ./web-api/app-settings.env

  reversi_ui:
    build:
      context: ui
    container_name: reversi_ui
    volumes:
      - ./ui:/projects
    depends_on:
      - reversi_web-api
    ports:
      - "4200:4200"

  reversi_e2e-test:
    build:
      context: ./e2e-test
    container_name: reversi_e2e-test
    depends_on:
      - reversi_web-api
      - reversi_ui
