CREATE ROLE reversi_user LOGIN PASSWORD 'reversi_user';

REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;

GRANT USAGE ON SCHEMA reversi TO reversi_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA reversi GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO reversi_user;
