spring:
  application:
    name: web-api
#  flyway:
#    enabled: false

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: ${DATASOURCE_URL}
#    username: ${DATASOURCE_USERNAME}
#    password: ${DATASOURCE_PASSWORD}
#    hikari:
#      maximum-pool-size: ${DATASOURCE_MAXIMUM_POOL_SIZE:10}
  r2dbc:
    url: r2dbc:h2:mem:///reversi_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  flyway:
    enabled: true
    url: jdbc:h2:mem:reversi_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
    locations: classpath:db/migration