spring:
  application:
    name: web-api

  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  flyway:
    enabled: true
    url: ${FLYWAY_URL}
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
    locations: classpath:db/migration
    schemas: reversi
    defaultSchema: reversi

app:
  auth:
    allowed-origins: ${ALLOWED_ORIGINS}
